- name: testBQ
  type: object
  path: $.values
  values:
      spent: $.sumCost     # static value
      vmnum: $.sumVM # dynamic value
      sumMemory: $.sumMemory
      sumCores: $.sumCores
      sumGPU: $.sumGPU
