go:
    version: 1.14
repository:
    path: github.com/ines-cruz/json_exporter
build:
    binaries:
        - name: json_exporter
    flags: -a -tags 'netgo static_build'
tarball:
    files:
        - LICENSE
