metrics:
- name: testBQ
  type: object
  path: $.values[*]
  labels:
    projectid: $.projectid
    month: $.month
  values:
    amountSpent: $.amountSpent
    numberVM: $.numberVM
    memoryMB: $.memoryMB
    CPUh: $.CPUh
    GPUh: $.GPUh


