metrics:
- name: testBQ
  type: object
  path: $.values
  values:
    spent: $.sumCost
    vmnum: $.sumVM
    sumMemory: $.sumMem
    sumCores: $.sumCores
    sumGPU: $.sumGPU
    projectid: $.projectid