metrics:
- name: testBQ
  type: object
  path: $.values[*]
  labels:
    projectid: $.projectid
  values:
    spent: $.sumCost
    vmnum: $.sumVM
    sumMemory: $.sumMem
    sumCores: $.sumCores
    sumGPU: $.sumGPU
