metrics:
- name: testBQ
  type: object
  path: $.projectid[*]
  projectid:
    amountSpent: $.amountSpent
    numberVM: $.numberVM
    memoryMB: $.memoryMB
    CPUh: $.CPUh
    GPUh: $.GPUh
    month: $.month


