metrics:
- name: testBQ
  type: object
  path: $.values[*]
  labels:
    month: $.month
  values:
    spent: $.amountSpent
    vmnum: $.numberVM
    sumMemory: $.memoryMB
    sumCores: $.CPUh
    sumGPU: $.GPUh
    projectid: $.projectid

