
scrape_configs:


  ## gather the metrics from third party json sources, via the json exporter
- job_name: json
  metrics_path: /probe
  scrape_interval: 1800s
  scrape_timeout: 30s
  static_configs:
    - targets:
      - http://localhost:8080/examples/output.json
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:7979
