global:
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 30s
    api_version: v1
rule_files:
- /etc/prometheus/alerts.yml
scrape_configs:
- job_name: json_exporter
  honor_timestamps: true
  scrape_interval: 3600s
  scrape_timeout: 30s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - localhost:7979
    - localhost:8080
  params:
    target: ["localhost:8080/examples/output.json"]
  relabel_configs:
    - source_labels: [__param_target]
      target_label: endpoint
      action: replace
