global:
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /etc/prometheus/alerts.yml
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - cloud-tracking.web.cern.ch:9090
    - cloud-tracking.web.cern.ch/
- job_name: json_exporter
  honor_timestamps: true
  scrape_interval: 5s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - cloud-tracking.web.cern.ch/
  params:
    target: ["http://cloud-tracking.web.cern.ch:8080/examples/output.json"]
  relabel_configs:
    - source_labels: [__param_target]
      target_label: endpoint
      action: replace
